name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  cilantro_DIR: ${{github.workspace}}/cilantro
  Pangolin_DIR: ${{github.workspace}}/Pangolin

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Pangolin
      uses: actions/checkout@v3
      with:
        repository: stevenlovegrove/Pangolin
        submodules: true
        path: ${{env.Pangolin_DIR}}

    - name: Install Pangolin dependencies
      run: ${{env.Pangolin_DIR}}/scripts/install_prerequisites.sh --package-manager apt recommended

    - name: Configure Pangolin
      run: cmake -B ${{env.Pangolin_DIR}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.Pangolin_DIR}}

    - name: Build Pangolin
      run: cmake --build ${{env.Pangolin_DIR}}/build --config ${{env.BUILD_TYPE}} -- -j8

    - name: Clone cilantro
      uses: actions/checkout@v3
      with:
        path: ${{env.cilantro_DIR}}

    - name: Configure cilantro
      run: cmake -B ${{env.cilantro_DIR}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPangolin_DIR=${{env.Pangolin_DIR}}/build -S ${{env.cilantro_DIR}}

    - name: Build cilantro
      run: cmake --build ${{env.cilantro_DIR}}/build --config ${{env.BUILD_TYPE}} -- -j8
