name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone cilantro
      uses: actions/checkout@v3

    - name: Clone Pangolin
      uses: actions/checkout@v3
      with:
        repository: stevenlovegrove/Pangolin
        submodules: true
        path: ${{github.workspace}}/Pangolin

    - name: Install Pangolin dependencies
      run: ${{github.workspace}}/Pangolin/scripts/install_prerequisites.sh --package-manager apt recommended

    - name: Configure Pangolin
      run: cmake -B ${{github.workspace}}/Pangolin/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}}/Pangolin

    - name: Build Pangolin
      run: cmake --build ${{github.workspace}}/Pangolin/build --config ${{env.BUILD_TYPE}} -- -j8

    - name: Configure cilantro
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DPangolin_DIR=${{github.workspace}}/Pangolin/build/

    - name: Build cilantro
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j8
